images:
  - name: images
    label: Images
    input: assets/img
    output: /assets/img
content:
  - name: posts
    label: Posts
    path: _posts
    type: collection
    view: 
      fields: [ title, date ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        type: date
        type: date
    
  