images:
  - name: images
    label: Images
    input: assets/img
    output: /assets/img
content:
  - name: posts
    label: Posts
    path: _posts
    type: collection
    view: 
      fields: [ title, subtitle, author, date, tags, body ]
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: string
      - name: author
        label: Author
        type: string
      - name: date
        label: date
        type: date
      - name: tags
        label: tags
        type: select
        options:
          multiple: true
          values: [ Cycling, Finances, Housing, Transit, Newsletter, Letters, Event ]
      - name: body
        label: Body
        type: rich-text
    
  