title: Strong Towns Ottawa
description: A website for Strong Towns Ottawa
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate-v2

# Pagination settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
  generate_all_posts: true
  all_posts_link_text: "View All Posts"
  all_posts_link_url: "/all-posts/"

# Beautiful Jekyll specific settings
avatar: assets/img/logo.png
favicon: assets/img/favicon.ico
show-avatar: true
description: A website for Strong Towns Ottawa
show-header: true
show-footer: true
show-social-icons: true
show-blog-link: false

# Additional head content
head-extra: |
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/custom.css">

# Navigation links
navbar-links:
  About Us: "about"
  Resources: "resources"

# Select which social network links to show in the footer
social-network-links:
  email: "info@strongtownsottawa.ca"
  github: Strong-Towns-Ottawa
  twitter: strongtownsott
  rss: true
  youtube: "@strongTownsOttawa"
  discord: "kHaVNgrcsG"
  facebook: "groups/751202843212260"

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "strongtownsottawa.ca"

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - index.md
  - .git
  - .gitignore 