---
title: Strong Towns Ottawa
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A website for Strong Towns Ottawa
baseurl: 
url: 
markdown: kramdown
remote_theme: daattali/beautiful-jekyll
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-remote-theme
- jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 5
  permalink: "/page:num/"
  title: ":title - page :num"
  limit: 10
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
  generate_all_posts: true
avatar: 
favicon: assets/img/favicon.ico
show-avatar: true
show-header: true
show-footer: true
show-social-icons: true
show-blog-link: false
site-css:
- "/assets/css/custom.css"
navbar-text-col: "#FFFFFF"
head-extra: |
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/custom.css">
  <script data-goatcounter="https://strongtownsottawa.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
navbar-links:
  Highlights: "/#Highlights"
  Articles: All_Posts
  Events: "/#Events"
  About Us: about
social-network-links:
  email: info@strongtownsottawa.ca
  github: Strong-Towns-Ottawa
  twitter: strongtownsott
  rss: true
  youtube: "@strongTownsOttawa"
  discord: kHaVNgrcsG
  facebook: groups/751202843212260
url-pretty: strongtownsottawa.ca
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- ".git"
- ".gitignore"
