title: Strong Towns Ottawa
description: A website for Strong Towns Ottawa
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Beautiful Jekyll specific settings
avatar: assets/img/logo.png
favicon: assets/img/favicon.ico
show-avatar: true
description: A website for Strong Towns Ottawa
show-header: true
show-footer: true
show-social-icons: true

# Additional head content
head-extra: |
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/custom.css">

# Navigation links
navbar-links:
  About Us: "about"
  Blog: "blog"
  Resources: "resources"
  Contact: "contact"

# Footer links
footer-links:
  twitter: strongtownsott
  github: Strong-Towns-Ottawa
  email: info@strongtownsottawa.ca

# Social media usernames
social-share:
  twitter: strongtownsott
  github: Strong-Towns-Ottawa
  email: info@strongtownsottawa.ca

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore 