title: Strong Towns Ottawa
description: A website for Strong Towns Ottawa
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Beautiful Jekyll specific settings
avatar: assets/img/logo.png
favicon: assets/img/favicon.ico
show-avatar: true
description: A website for Strong Towns Ottawa
footer-links:
  twitter: strongtownsott
  github: Strong-Towns-Ottawa
  email: info@strongtownsottawa.ca

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore 