source "https://rubygems.org"

gem "jekyll"
gem "webrick"
gem "csv"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "beautiful-jekyll-theme"
gem "base64"
gem "logger"
gem "bigdecimal"
gem "jekyll-remote-theme"
gem "jekyll-paginate-v2" 
gem 'jekyll-archives'