name: Build and Deploy Jekyll to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby & Fix SSL
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates libssl-dev
        sudo update-ca-certificates --fresh
        
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
        
    - name: Build site
      run: bundle exec jekyll build
      env:
        SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
        JEKYLL_SSL_NO_VERIFY: true
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages