name: Build and Deploy Jekyll to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest  #test1
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby & SSL
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates libssl-dev curl
        sudo update-ca-certificates --fresh
        
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
        
    - name: Build site
      run: |
        export JEKYLL_SSL_NO_VERIFY=true
        export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
        bundle exec jekyll build
        
    - name: Verify _site contents
      run: |
        echo "_site directory contents:"
        ls -la _site/
        echo "First few files in _site:"
        find _site -type f | head -20
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages